=== MPEGGroup/DASHSchema/verification/FourCC-Validation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root-element SYSTEM "../DASH-entities.dtd">
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Tests">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="FourCC">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="&FourCC;"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MPEGGroup/DASHSchema/verification/FourCC-validation.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FourCC-validation.xsd">

	<!-- a selection of valies from mp4ra.org -->
	<FourCC>Mp4a</FourCC>
	<FourCC>caac</FourCC>
	<FourCC>3gp4</FourCC>
	<FourCC>dxo </FourCC>
	<FourCC>jxl </FourCC>
	<FourCC>qt  </FourCC>
	<FourCC>XAVC</FourCC>
	<FourCC>mpd </FourCC>
	<FourCC>MPEG</FourCC>
	<FourCC>uri </FourCC>
	<FourCC>jsxH</FourCC>
	<FourCC>rICC</FourCC>
	<FourCC>sha1</FourCC>
</Tests>
