=== MPEGGroup/DASHSchema/verification/type-IPv6URL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root-element SYSTEM "../DASH-entities.dtd">
 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="Tests">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="v6url">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="(&Scheme;:(//(&User;(:&Password;)?@)?&IPv6Host;&Port;?&Path;*/?|&PathNoAuthority;)|(&RelativePath;/?|&AbsolutePath;/?))&Query;?&Fragment;?"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element> 

			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MPEGGroup/DASHSchema/verification/type-IPv6URL.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="type-IPv6URL.xsd">


<v6url>http://[e80:123:123:123:8939:7684:d84b:a5a4]</v6url>

<!-- examples from https://www.ietf.org/rfc/rfc2732.txt -->
<v6url>http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html</v6url>
<v6url>http://[1080:0:0:0:8:800:200C:417A]/index.html</v6url>

<v6url>http://[::192.9.5.5]/ipng</v6url>
<v6url>http://[::ffff:129.144.52.38]:80/index.html</v6url>
<v6url>http://[2010:836B:4179::836B:4179]</v6url>

<v6url>http://[1080::8:800:200C:417A]/foo</v6url>
<v6url>http://[3ffe:2a00:100:7031::1]</v6url>


</Tests>
